language: cpp # To build/install D compilers
before_install:
  - chmod +x travis_scripts/*.sh

install:
  - . ./travis_scripts/try_install_dmd.sh
  - . ./travis_scripts/try_install_ldmd2.sh
  - $DC | head -3

script:
  - make unittest DC=$DC

env:
  - DC=dmd
  - DC=ldmd2
