language: cpp # To build/install D compilers
before_install:
  - wget http://downloads.dlang.org/releases/2013/dmd_2.064.2-0_amd64.deb
  - wget https://github.com/ldc-developers/ldc/releases/download/v0.12.1/ldc2-0.12.1-linux-x86_64.tar.gz

install:
  - if [ "$DC" == "dmd" ]
  - then
  -   sudo apt-get install gcc-multilib
  -   sudo dpkg -i dmd_2.064.2-0_amd64.deb
  - fi
  -
  - if [ "$DC" == "ldmd2" ]
  - then
  -   gunzip ldc2-0.12.1-linux-x86_64.tar.gz
  -   export PATH=$PATH:`pwd`/ldc2-0.12.1-linux-x86_64/bin
  - fi

script:
  - make unittest DC=$DC

env:
  - DC=dmd
  - DC=ldmd2
